CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -Os -flto -ffunction-sections -fdata-sections
LDFLAGS = -Wl,--gc-sections -Wl,--strip-all
LIBS = -lyandex_parser -lcurl

demo: demo.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o demo demo.c $(LIBS)

run: demo
	./demo.sh

clean:
	rm -f demo *.jpg sunset/ nature/ cats/ dogs/

.PHONY: run clean
